version: '3.4'

services:
  db:
    image: mysql:5.7
    container_name: ${APP_NAME}-db
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - dbdata:/var/lib/mysql

  app:
    build:
      context: .
      target: dev
    env_file: .env
    image: arpegio:${APP_VERSION}
    container_name: ${APP_NAME}-app
    command:
      - /bin/sh
      - -c
      - |
        sleep 15
        npx sequelize-cli db:migrate
        npx sequelize-cli db:seed:all
        npm run dev
    depends_on:
      - db
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - ./back/:/app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}-phpmyadmin
    links:
      - db
    env_file: .env
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}
      - PMA_ARBITRARY=${PMA_ARBITRARY}
    restart: always
    ports:
      - ${PMA_WEB_PORT}:80

volumes:
  dbdata: